#take user input with method called input()

print("Hi")
print("Please enter your first and last name")
first_name =input("first name"+" ")
last_name =input("last name"+" ")
full_name = first_name.capitalize() +  " " + last_name.capitalize()
print("your full name is...")
print(full_name)
print("what is your age in years")
age =int(input("age"+" "))
print(full_name + " " +"is"+" "+str(age)+" "+"years old")
print("please enter your first line of address")
houseorflat_number = int(input('building number'+" "))
street = str(input('street name'+" "))
print("please enter your postcode")
postcode = input()
print("please add your contact number")
contact_number = input()
print(contact_number.isdigit())
print("what is your salary per annum in sterling pounds")
salary = input()
print(salary.isdigit())
